apiVersion: v1
kind: Service
metadata:
  name: crossview-service
  namespace: crossview
  labels:
    app: crossview
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
    nodePort: 30951
  selector:
    app: crossview